### ISSUE TITLE
Backcalculation

### ISSUE THREAD

**Issue by Mostafa-Nakhaei** [asmusskar/ALVA#2]
Hi
Mostafa Again. 
For your back-calculation program in `o = 1/length(alva.dFWD)*sqrt(dd*dd');`  should `1/length()` not be in the `sqrt()` function? 
Thanks
Mostafa

**Comment by asmusskar** [comment]
Hi. 
This one is often used in pavement engineering (https://trid.trb.org/view/359589), but its just a scaling factor, don't think it will make a big difference.. could influence the convergence rate of the solver dependent on type you choose..
Asmus
